---
# tasks file for ufw

- name: Assertions
  assert:
    that: ansible_pkg_mgr == 'apt'

- name: apt install ufw
  apt:
    name: ufw
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Rate limit SSH
  ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Enable UFW
  ufw:
    policy: '{{ ufw_policy }}'
    state: enabled
